---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.9.0
    hooks:
      - id: ansible-lint
