---
- name: Create user with ssh key
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash
    password: "{{ password_hash }}"
    update_password: on_create
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  become: true
  register: created_user

- name: Disable sudo explicit group check
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^Defaults\\s*verifypw"
    line: "Defaults verifypw=any"
    state: present
  become: true

- name: Add authorized keys from github
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ keyurl }}"
  become: true
- name: "Add sudoers rules for {{ username }}"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ username }}"
    content: |
      {{ username }} ALL=(ALL) NOPASSWD: ALL
    mode: 0440
    owner: root
    group: root
    validate: "visudo -cf %s"
  become: true
