---
- name: Clone dotfiles repo
  vars:
    dotfiles_repo_local_destination: "{{ created_user.home }}/dotfiles"
    dotfiles_repo: "https://github.com/galbitz/dotfiles.git"
    dotfiles_repo_version: main
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: false
  register: git_results
  become: true
  become_user: "{{ username }}"

- name: Install dotfiles
  vars:
    dotfiles_repo_local_destination: "{{ created_user.home }}/dotfiles"
  ansible.builtin.command:
    cmd: "{{ dotfiles_repo_local_destination }}/install.sh"
    creates: "{{ created_user.home }}/.bashrc_extra"
  when: git_results.changed
  become: true
  become_user: "{{ username }}"
