---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - openssh-client
      - curl
      - wget
      - git
      - sudo
    state: present

- name: Create user
  ansible.builtin.include_tasks: create_user.yml
- name: Dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
