---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - openssh-client
      - curl
      - wget
      - git
      - sudo
      - tmux
      - htop
      - acl
    state: present
  become: true

- name: Create user
  ansible.builtin.include_tasks: create_user.yml
- name: Dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
