---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - openssh-client
      - curl
      - wget
      - git
    state: present

- name: Create user
  ansible.builtin.include_tasks: create_user.yml
- name: Configure Starship prompt
  ansible.builtin.include_tasks: configure_prompt.yml
- name: Dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
